version: "3"

services:
  holodos_server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: app_server
    ports:
      - "8001:4000"

  holodos_client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: app_client
    ports:
      - "80:3000"

