version: "3"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: app_server
    ports:
      - "8001:8001"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: app_client
    ports:
      - "80:3000"
