# Generated by Django 4.1.7 on 2023-03-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_searchitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="searchitem", name="amount",),
    ]
