# Generated by Django 4.1.7 on 2023-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Технічна"),
                    ("NOT_TECHnICAL", "Не технічна"),
                    ("OTHER", "Інша"),
                ],
                max_length=20,
            ),
        ),
    ]
